name: CI

on:
  push:
    branches: [release]
  pull_request:
    branches: [release]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.3'
          cache: false        

      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '24'
              

      - name: Install Task
        uses: arduino/setup-task@v3
        with:
          version: 3.x

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          args: ./src/...
        continue-on-error: true

      - name: Run tests
        run: task test

      - name: Build binaries
        run: task build-all