name: Publish to npm

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Verify Tag Exists on Release Branch
        id: branch-filter
        run: |
          if git branch -r --contains ${{ github.ref_name }} | grep -q 'origin/release'; then
            echo "Target tag belongs to the release branch. Proceeding."
            echo "is_release=true" >> $GITHUB_OUTPUT
          else
            echo "Tag was created outside of the release branch. Skipping execution."
            echo "is_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Go
        if: steps.branch-filter.outputs.is_release == 'true'
        uses: actions/setup-go@v6
        with:
          go-version: "1.26.3"
          cache: false

      - name: Set up Node.js
        if: steps.branch-filter.outputs.is_release == 'true'
        uses: actions/setup-node@v7
        with:
          node-version: "25"
          cache: "npm"

      - name: Install Task
        if: steps.branch-filter.outputs.is_release == 'true'
        uses: arduino/setup-task@v3
        with:
          version: 3.x

      - name: Package npm tarballs
        if: steps.branch-filter.outputs.is_release == 'true'
        run: task package-npm

      - name: Setup npm authentication
        if: steps.branch-filter.outputs.is_release == 'true'
        run: |
          echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish packages to NPM
        if: steps.branch-filter.outputs.is_release == 'true'
        run: |
          if [[ "${{ github.ref_name }}" == *"alpha"* ]]; then
            NPM_TAG="alpha"
          else
            NPM_TAG="latest"
          fi

          echo "Publishing with npm tag: $NPM_TAG"

          for dir in npm/star-run-*/ npm/star-run/; do
            if [ -d "$dir" ]; then
              (cd "$dir" && npm stage publish --access public --tag $NPM_TAG )
            fi
          done
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
